name:                advent-of-code-api
version:             0.1.2.0
github:              "mstksg/advent-of-code-api"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.0 && < 8.8

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Advent of Code REST API bindings
category:            Web

description: |
    Haskell bindings for Advent of Code REST API.  Please use responsibly!
    See README.md or "Advent" module for an introduction and tutorial.

    Requires libcurl.

ghc-options:
- -Wall
- -Wcompat
- -Werror=incomplete-patterns

library:
  source-dirs: src
  exposed-modules:
  - Advent
  dependencies:
  - base >= 4.9 && < 5
  - containers
  - curl
  - deepseq
  - directory
  - filepath
  - finite-typelits
  - mtl
  - taggy
  - text
  - time
  - uri-encode
