name:                advent-of-code-api
version:             0.1.2.3
github:              "mstksg/advent-of-code-api"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.0

extra-source-files:
- README.md
- CHANGELOG.md
- test-data/*.txt

# Metadata used when publishing your package
synopsis:            Advent of Code REST API bindings
category:            Web

description: |
    Haskell bindings for Advent of Code REST API.  Please use responsibly!
    See README.md or "Advent" module for an introduction and tutorial.

    Requires libcurl.

ghc-options:
- -Wall
- -Wcompat
- -Werror=incomplete-patterns

dependencies:
- base >= 4.9 && < 5
- text
- directory
- filepath

library:
  source-dirs: src
  exposed-modules:
  - Advent
  dependencies:
  - http-client
  - aeson
  - stm
  - http-media
  - bytestring
  - attoparsec
  - containers
  - http-client-tls
  - cookie
  - curl
  - deepseq
  - finite-typelits
  - mtl
  - servant
  - servant-client
  - tagsoup
  - time
  - uri-encode

tests:
  advent-of-code-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-api
    - HUnit
